crupzi/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

#from users.views import connect, newaccount, invite, invitation_request, complete_registration, account_configuration, account_operations, profile


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'crupzi.views.index', name='index'),
    url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/favicon.ico'}),
    url(r'^apple-touch-icon-precomposed\.png$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/apple-touch-icon-precomposed.png'}),
    url(r'^apple-touch-icon\.png$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/apple-touch-icon.png'}),
    url(r'^testfoursquare6/$', 'crupzi.views.testfoursquare', name='testfoursquare'),
    url(r'^testfoursquare-montesion/$', 'crupzi.views.testfoursquare_montesion', name='testfoursquare_montesion'),
    url(r'^beneficios/$', 'crupzi.views.features', name='features'),
    url(r'^comercios/$', 'crupzi.views.commerce', name='commerce'),
    url(r'^contacto/$', 'crupzi.views.contact', name='contact'),
    url(r'^nosotros/$', 'crupzi.views.us', name='us'),
    url(r'^soporte/$', 'crupzi.views.support', name='support'),
    url(r'^inicio/$', 'crupzi.views.home', name='home'),
    url(r'^tutoriales/$', 'django.views.generic.simple.redirect_to', {'url': 'http://www.youtube.com/playlist?list=PLhaYUqqgOkI3DduxrDZXw4Pt5UlO9guWX'}),
    url(r'^busqueda/$', 'deals.views.mobilesearch', name='mobilesearch'),
    url(r'^in/$', 'crupzi.views.new_user', name='new_user'),
    url(r'^logout/', 'crupzi.views.logout', name='logout'),
    url(r'^send_invitation/', 'crupzi.views.send_invitation', name='send_invitation'),
    url(r'^compartir/', 'crupzi.views.share', name='share'),
    url(r'^mobile/activacion/', 'crupzi.views.mobile_activation', name='mobile_activation'),
    url(r'^mobile/login/', 'crupzi.views.mobile_login', name='mobile_login'),
    url(r'^mobile/(?P<pub>[-\w]+)/solicitud/', 'crupzi.views.mobile_request', name='mobile_request'),
    url(r'^mobile/(?P<pub>[-\w]+)/', 'crupzi.views.mobile_pubs', name='mobile_pubs'),
    url(r'^comercios/connect/', 'crupzi.views.business_connect', name='business_connect'),
    url(r'^comercios/login/', 'crupzi.views.business_login', name='business_login'),
    url(r'^comercios/demo/', 'crupzi.views.business_login_demo', name='business_login_demo'),
    url(r'^comercios/inscripcion/', 'crupzi.views.business_signup', name='business_signup'),
    url(r'^comercios/logout/', 'crupzi.views.business_logout', name='business_logout'),
    url(r'^sendyapi/subscribe/', 'crupzi.views.sendy_subscribe', name='sendy_subscribe'),
    url(r'^sendyapi/unsubscribe/', 'crupzi.views.sendy_unsubscribe', name='sendy_unsubscribe'),
    url(r'^sendynewsletter/subscribe/', 'crupzi.views.sendy_subscribe_newsletter', name='sendy_subscribe_newsletter'),
    url(r'^suscripcion-exitosa-newsletter/', 'django.views.generic.simple.direct_to_template', {'template': 'mails/sendy-subscriptiondoubleopt.html', 'extra_context':  {'page': 'newsletter'} }  ),
    url(r'^suscripcion-exitosa-blog/', 'django.views.generic.simple.direct_to_template', {'template': 'mails/sendy-subscriptiondoubleopt.html', 'extra_context':  {'page': 'blog'}} ),
    url(r'^especiales/(?P<which>[-\w]+)/', 'crupzi.views.specials', name='specials'),
    url(r'', include('social_auth.urls')),
    url(r'', include('fakes.urls')),
    url(r'', include('deals.urls')),
    url(r'', include('companies.urls')),
    url(r'', include('users.urls')),
    url(r'^login/$', 'crupzi.views.login_user', name='crupzi_login'),
    # url(r'^crupzi/', include('crupzi.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)

deals/urls.py
from django.conf.urls import patterns, include, url
from deals.views import get_public_data, get_deal, save_deal, remove_deal, deal_search, search_box_input, search_get, single_deal, get_social, search_query, get_user_deal

urlpatterns = patterns('',
	url(r'^busqueda/', deal_search, name='deal_search'),
	url(r'^descuentos/(?P<slug>[-\w]+)/', single_deal, name='single_deal'),
	url(r'^search-box/get/(?P<what>\w+)/', search_box_input, name='search_box_input'),
	url(r'^search/query/', search_query, name='search_query'),
	url(r'^search/get/(?P<page>\w+)/', search_get, name='search_get'),
	url(r'^user-deals/get/code/(?P<deal_id>\w+)/', get_user_deal, name='get_user_deal'),
	url(r'^deals/get/code/(?P<deal_id>\w+)/', get_deal, name='get_deal'),
	url(r'^deals/get/social/(?P<deal_id>\w+)/', get_social, name='get_social'),
	url(r'^deals/get/(?P<category>\w+)/(?P<tab>\w+)/', get_public_data, name='get_public_data'),
	url(r'^deals/save/(?P<deal_id>\w+)/', save_deal, name='save_deal'),
	url(r'^deals/remove/(?P<deal_id>\w+)/', remove_deal, name='remove_deal'),
)

users/forms.py
# -*- coding: utf-8 -*-
import datetime, os, urllib, urllib2
from PIL import Image
from cropresize import crop_resize
from django import forms
from django.forms import ModelForm
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from users.models import Country, City, Profile

'''--------------------
 Complete registration
--------------------'''

countries = list()
countries.append(tuple(('','')))
query_set = Country.objects.values('id','name').filter(id__gte=1)
print query_set
for country in query_set:
	countries.append(tuple((str(country.get('id')), str(country.get('name')))))
cities = list()
query_set = City.objects.values('id','name')
for city in query_set:
	cities.append(tuple((str(city.get('id')), city.get('name').encode('utf-8'))))

class CompleteRegistrationForm(forms.Form):
	GENDER_CHOICES = (('',''),('M','Masculino'),('F','Femenino'))
	STUDIES_CHOICES = (('P','Primaria'),('S','Secundaria'),('U','Universitaria'),('M','Maestría'),('D','Doctorado'))
	RELATIONSHIP_CHOICES = (('S','Soltero'),('R','En una relación'),('C','Casado'))
	countries = list()
	countries.append(tuple(('','')))
	query_set = Country.objects.values('id','name').filter(id__gte=1)
	for country in query_set:
		countries.append(tuple((str(country.get('id')), str(country.get('name')))))
	cities = list()
	query_set = City.objects.values('id','name')
	for city in query_set:
		cities.append(tuple((str(city.get('id')), city.get('name').encode('utf-8'))))
	username = forms.CharField(label='Usuario', required=True, error_messages={'required': 'Ingresa tu nombre de usuario'},widget=forms.TextInput({ "placeholder": "Nombre de usuario" }))
	email = forms.CharField(label='Correo electrónico', required=True, error_messages={'required': 'Ingresa tu correo electrónico'},widget=forms.TextInput({ "placeholder": "usuario@dominio" }))
	first_name = forms.CharField(label='Nombres', required=True, error_messages={'required': 'Ingresa tu nombre'},widget=forms.TextInput({ "placeholder": "Nombres" }))
	last_name = forms.CharField(label='Apellidos', required=True, error_messages={'required': 'Ingresa tus apellidos'},widget=forms.TextInput({ "placeholder": "Apellidos" }))
	birthday = forms.DateField(label='Fecha de Nacimiento', input_formats=["%d/%m/%Y"], required=True, error_messages={'required': 'Ingresa tu fecha de nacimiento'},widget=forms.TextInput({ "placeholder": "dd/mm/AAAA" }))
	gender = forms.ChoiceField(label='Género', choices=GENDER_CHOICES, required=True, error_messages={'required': 'Ingresa tu género'}, widget=forms.Select({'style':'width:295px;'}))
	country = forms.ChoiceField(label='País', choices=countries, required=True, error_messages={'required': 'Ingresa tu país'}, widget=forms.Select({'style':'width:295px;'}))
	city = forms.ChoiceField(label='Departamento', required=True, choices=cities, error_messages={'required': 'Ingresa tu departamento'}, widget=forms.Select({'style':'width:295px;'}))

	def clean_username(self):
		username = self.cleaned_data.get('username', '')
		email = self.cleaned_data.get('email','')
		haystack = ['OSCAR','AREVALO','JOSEDANIEL','ZARATE']
		needle = username.upper()
		if needle in haystack:
			print 'ValidationError'
			raise forms.ValidationError("El nombre de usuario ya ha sido registrado.")
		try:
			user = User.objects.get(username=username)
			if user is not None:
				raise forms.ValidationError("El nombre de usuario ya ha sido registrado.")
		except User.DoesNotExist:
			pass
		return username

	def clean_email(self):
		email = self.cleaned_data.get('email','')
		try:
			user = User.objects.get(email=email)
			if user is not None:
				raise forms.ValidationError("El email ya ha sido registrado")
		except User.DoesNotExist:
			pass
		return email

	def clean_birthday(self):
		birthday = self.cleaned_data.get('birthday')
		try:
			bday = birthday.strftime('%d/%m/%Y')
			datetime.datetime.strptime(bday, '%d/%m/%Y')
			return birthday
		except Exception,e:
			raise forms.ValidationError("La fecha ingresada no es correcta.")

'''--------------------------
 Account (profile and stuff)
--------------------------'''
class ProfileForm(forms.Form):

	#username = forms.CharField(label='Nombre de usuario', required=True)
	first_name = forms.CharField(label='Nombres', required=True, error_messages={'required': 'Ingresa tu nombre'})
	last_name = forms.CharField(label='Apellidos', required=True,error_messages={'required': 'Ingresa tu apellido'})
	#email = forms.EmailField(label='Email', required=True, error_messages={'required':'Ingresa tu email', 'invalid': 'Ingresa un email valido.'})
	birthday = forms.DateField(label='Fecha de Nacimiento', input_formats=["%d/%m/%Y"], required=True, error_messages={'required': 'Ingresa tu fecha de nacimiento', 'invalid':'Ingresa una fecha valida.'})
	gender = forms.ChoiceField(label='Género', choices=(('M','Masculino'),('F','Femenino')))
	country = forms.ChoiceField(label='País', choices=countries, required=True, error_messages={'required': 'Ingresa tu país'})
	city = forms.ChoiceField(label='Departamento', required=True, choices=cities, error_messages={'required': 'Ingresa tu departamento'})
	display = forms.ImageField(label='Display', required=False)
	newsletter = forms.BooleanField(label='Incluirme en lista de correos', required=False)
	notice = forms.BooleanField(label='Incluirme en envío de comunicados', required=False)

	'''
	def clean_username(self):
		username = self.cleaned_data.get('username', '')
		try:
			user = User.objects.get(username=username)
			if user is not None:
				raise forms.ValidationError("El nombre de usuario ya ha sido registrado.")
		except User.DoesNotExist:
			pass
		return username
	'''

	def clean_birthday(self):
		birthday = self.cleaned_data.get('birthday')
		try:
			bday = birthday.strftime('%d/%m/%Y')
			datetime.datetime.strptime(bday, '%d/%m/%Y')
			return birthday
		except Exception,e:
			print e
			raise forms.ValidationError("La fecha ingresada no es correcta.")


	def save(self, user, files):
		username = user.username
		profile = Profile.objects.get(user=user)
		#display uploads.
		display = files.get('display')
		if display is not None:
			path = os.path.join(settings.UPLOAD_URL,display.name)
			destination = open(path,'wb+')
			for chunk in display.chunks():
				destination.write(chunk)
			destination.close()
			try:
				img = Image.open(path)
				resized_img = crop_resize(img,(60,60))
				resized_img.save(os.path.join(settings.UPLOAD_URL,'60x60_'+display.name))
				setattr(profile, 'display','/static/uploads/displays/60x60_'+display.name)
				company.save()
			except Exception,e:
				print e
		#setattr(user, 'username', self.cleaned_data['username']
		setattr(user, 'first_name', self.cleaned_data['first_name'])
		setattr(user, 'last_name', self.cleaned_data['last_name'])
		#setattr(user, 'email', self.cleaned_data['email'])
		setattr(profile, 'birthday', self.cleaned_data['birthday'])
		setattr(profile, 'country_id', self.cleaned_data['country'])
		setattr(profile, 'city_id', self.cleaned_data['city'])
		form_newsletter = self.cleaned_data['newsletter']
		form_notice = self.cleaned_data['notice']
		if profile.newsletter != form_newsletter:
			setattr(profile, 'newsletter', form_newsletter)
			post_data = [('email',user.email),('list','2'), ('boolean','true')]
			action = 'subscribe' if form_newsletter else 'unsubscribe'
			result = urllib2.urlopen('http://www.crupzi.com/sendy/'+action, urllib.urlencode(post_data))
			content = result.read()
		if profile.notice != form_notice:
			setattr(profile, 'notice', form_notice)
			post_data = [('email',user.email),('list','5'), ('boolean','true')]
			action = 'subscribe' if form_notice else 'unsubscribe'
			result = urllib2.urlopen('http://www.crupzi.com/sendy/'+action, urllib.urlencode(post_data))
			content = result.read()
		user.save()
		profile.save()

crupzi/templates/app/no-user-newsletter.html
<strong><span style="color:#eb4022;">&iexcl;Reg&iacute;strate para ganar un unicornio!</span></strong><br> (Y una suscripci&oacute;n a nuestros correos semanales con los mejores descuentos)<hr style="margin:5px 0 10px 0;"><form onsubmit="return false;" id="form-newsletter"><input type="text" name="username" id="news-username" placeholder="Nombre" style="width:150px;"/> <input type="text" name="email" id="news-email" placeholder="Email" style="width:150px;"/><input type="text" name="message" id="news-message" style="display:none;"/><button class="btn btn-primary" style="margin-top:-10px; margin-left:10px;" name="btn-newsletter" id="btn-newsletter">Suscr&iacute;beme</button></form><div style="margin-top:-20px;">Recibir&aacute;s un correo para confirmar tu suscripci&oacute;n. Odiamos el spam, amamos el tocino</div><div class="alert alert-success" id="newsletter-success" style="display:none;"><strong>&iexcl;Excelente!</strong><br>Ahora solo revisa tu correo y confirma tu suscripci&oacute;n dando clic en el enlace</div><div class="alert alert-error" id="newsletter-error" style="display:none;"><strong>&iexcl;Rayos!</strong><br>Algo sucedi&oacute;, si ya eres usuario de Crupzi, probablemente ya est&aacute;s inscrito. <br>Si no, int&eacute;ntalo nuevamente</div>

crupzi/templates/app/no-user-notification.html
<strong><span style="color:#eb4022;">&iquest;Quieres saber algo genial?</span></strong><hr style="margin:5px 0 10px 0;">Para utilizar crupzi.com <strong>no necesitas comprar <br>cupones o imprimir algún comprobante</strong>. <br>Únicamente menciona el descuento en el comercio <br>seleccionado  y listo. S&iacute;, es así de fácil.<br><br>Ingresa con tu cuenta de:<br><a href="http://www.crupzi.com/login/facebook/" class="floatleft"><img class="index-icon" src="/static/images/facebook.png"/></a><a href="http://www.crupzi.com/login/twitter/" class="floatleft" style="margin-left:10px;"><img class="index-icon" src="/static/images/twitter.png"/></a><a href="http://www.crupzi.com/login/google-oauth2/" class="floatleft" style="margin-left:10px;"><img class="index-icon" src="/static/images/google.png"/></a><br><br><br>Si tienes alguna duda puedes visitar nuestra secci&oacute;n <br>de <span class="blockAlertA"><a href="/soporte/" target="_blank"><strong>Preguntas Frecuentes</strong></a></span>

crupzi/templates/app/select-resources.html
{% regroup resources by entity.name as res_list %}
{% for entity in res_list %}
    <optgroup label='{{ entity.grouper }}'>
    {% for item in entity.list %}
          <option value='{{item.id}}'>{{entity.grouper}} - {{item.name}}</option>
    {% endfor %}
    </optgroup>
{% endfor %}
<optgroup label='Descuentos que no requieren tarjeta'><option value='0'>Sin tarjeta</option></optgroup>

crupzi/templates/app/user-profile.html
{% extends 'app/app-base.html' %}
{% load deals_filters %}

{% block user-header %}

{% endblock %}

{% block sub-header %}
	<div class='container'>
	</div>
{% endblock %}

{% block content %}

<style type="text/css">

.nav-tabs.nav-stacked > li > a {
	border: 1px solid #ddd;
	-webkit-border-radius: 0;
	-moz-border-radius: 0;
	border-radius: 0;
	background: #fff;
	padding-top:0.7em;
	padding-bottom: 0.7em;
}

.nav-tabs > .active > a, .nav-tabs > .active > a:hover {
	color: #333;
	cursor: default;
	background-color: #fff;
	border: 1px solid #E0DCBB;
	border-bottom-color: transparent;
	font-weight: bold;
}

.main-container{
	background:#fff; padding: 1em;
	border: 1px solid #ddd;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	-webkit-box-shadow: none;
	box-shadow: none;
}

.sub-container{
	padding: 1em; 
	margin-left: -1em;
	margin-right: -1em;
}
.border-bottom{
	border-bottom:1px solid #ddd;
}
.subscription-title{
	font-size: 1.5em; font-weight:bold;
	max-width: 300px;
	white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}

</style>

<div class='container' style='padding-bottom:200px; background:#f5f5f5;'>
	<div style='' class='alpha_body'>
      <div class='app-header'>
        <div class='floatleft'><a href="/"><img src="/static/images/landing/logo.png"></a></div>
        <div class='floatright'>
          <ul class="tabs nav nav-pills nav-pills-app app" id='ul-home'>
          	<li><a href="/inicio"><i class='icon-home icon-white'></i></a></li>
            <li><a href="/comercios/lista/" data-target="tab">Comercios</a></li>
            <li><a href="http://blog.crupzi.com" data-target="tab" target='_blank'>Blog</a></li>
            <li><a href="/mis-descuentos/" data-target="tab">Mis Descuentos</a></li>
            <li>
              {% if profile.display %}
              <div class='floatleft' style=''>
                <img src="{{ profile.display }}" width='32px'>
              </div>
              {% endif %}
              <div class='floatright' style='text-align:right; padding:0 0 0 0em; max-height:35px; margin-top:-5px;  '>
                <div>
                  <div style='margin:0; text-align:center;'><span style='color:#fff; font-size:1.1em;'>Bienvenido</span></div>
                  <ul class="nav nav-pills nav-pills-user" style='margin-top:-10px;'>
                    <li class="dropdown active">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          {{ user.username }}<b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu  pull-right">
                        <li><a href="/cuenta/perfil">Editar perfil</a></li>
                        <li><a href="/logout">Salir</a></li>
                      </ul>
                    </li>
                  </ul>

                </div>
              </div>
              <div style='clear:both;'></div>
            </li>          
          </ul>
        </div>
        <div style='clear:both;'></div>
      </div>
      
    </div>
    <div style="margin-top:60px;">
	    <div class="span5" style="">
	    	<div style="margin-left:40px;">
		    	<div class="main-container">
		    		<div class="floatleft">
		    			{% if profile %}
							{% if profile.display %}
								<img src="{{profile.display}}" width='60' style='margin-right:20px;'>
							{% endif %}
						{% endif%}
		    		</div>
		    		<div class="floatleft" style="line-height:1.5;">
		    			<span class='bold' style='font-size: 1.5em;'>{{user.username}}</span><br>
		    			<span class="" style='font-size: 1em;'>{{user.email}}</span><br>
		    		</div>
		    		<div style="clear:both;"></div>
		    	</div>
		    	<div class="" style="margin-top:20px;">
		    		<ul class="nav nav-tabs nav-stacked tabs">
		    			<li class="active"><a href="#tab-profile" data-toggle="tab"><i class="icon-chevron-right pull-right"></i>Perfil</a></li>
		    			<li><a href="#tab-subscriptions" data-toggle="tab"><i class="icon-chevron-right pull-right"></i>Mis suscripciones</a></li>
		    			<li><a href="#tab-suggestions" data-toggle="tab"><i class="icon-chevron-right pull-right"></i>Mis recomendaciones</a></li>
		    		</ul>
		    	</div>
	    	</div>
	    </div>
	    <div class='span7 tab-content' >
			<div id="tab-profile" class="tab-pane active">
				<div class='main-container' style="">
					<div style="" class="sub-container border-bottom">
						<span style="font-weight:bold; font-size:2em;">Perfil</span><br>
					</div>	
					<div class='sub-container' style="padding:1em;">
						<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
							{{ form.non_field_errors }}
							{% for field in form %}
								<div class="fieldWrapper inline-fields">
									{{ field.errors }}
									{% if field.name == 'newsletter' or field.name == 'notice' %}
										<div class='floatleft'>{{ field }}</div>
										<div class='floatleft' style='width:40%; margin:0.8em 0 0 12px;'>{{ field.label_tag }}</div>
										
									{% else %}
										<div class='inline-label floatleft' style='width:35%;'>{{ field.label_tag }}</div>
										<div class='inline-input floatleft'>{{ field }}</div><br>
									{% endif %}
									<div style='clear:both;'></div>
								</div>
							{% endfor %}
							<div style='padding-top: 1em;'>
								<input type="submit" value="Guardar" class='btn btn-black'/>
							</div>
						</form>
					</div>
				</div>
			
			</div>
			<div class="tab-pane main-container" id="tab-subscriptions" style="background:#fff;">
				<div style="" class="sub-container border-bottom">
					<span style="font-weight:bold; font-size:2em;">Mis suscripciones</span><br>
					<span>Recibir&aacute;s notificaciones de estos comercios</span>
				</div>
				{% if subscriptions %}
					{% for item in subscriptions %}
						<div data-companyid="{{ item.id }}" class="sub-container {% if not forloop.last %}border-bottom{% endif %}">
							<div class="floatleft" style="width:400px;">
								<div class="floatleft">
									<img src="/static/images/companies/logos_56/56x56_{{item.logo}}" style="border: 1px solid #f5f5f5; padding:5px;">
								</div>
								<div class="floatleft" style="line-height:1.2; margin: 10px 1em 0 1em;">
									<span class="subscription-title">{{ item.name }}</span><br>
									<p style="font-size:1.2em;">{{ item.categories|joinby:" • "}}</p>
								</div>
								<div style="clear:both;"></div>
							</div>
							<div class="floatleft" style="margin-top:20px;">
								<a class="btn btn-following-desktop" href="javascript:void(0);" style=" width:67px;" onclick="javascript:unsubscribe({{ item.id }});"><i class="fa fa-check-circle"></i> Eliminar</a>
								<a class="btn btn-subscribe-desktop" href="javascript:void(0);" style=" width:67px; display:none;" onclick="javascript:subscribe({{ item.id }});"><i class="fa fa-plus-circle"></i> Suscr&iacute;beme</a>
							</div>
							<div style="clear:both;"></div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
			<div class="tab-pane main-container" id="tab-suggestions" style="background:#fff;">
				<div style="" class="sub-container border-bottom">
					<span style="font-weight:bold; font-size:2em;">Mis recomendaciones</span><br>
					<span>&iquest;Quieres recibir notificaciones de estos comercios?</span>
				</div>
				{% if non_subscriptions %}
					{% for item in non_subscriptions %}
						<div data-companyid="{{ item.id }}" class="sub-container {% if not forloop.last %}border-bottom{% endif %}">
							<div class="floatleft" style="width:400px;">
								<div class="floatleft">
									<img src="/static/images/companies/logos_56/56x56_{{item.logo}}" style="border: 1px solid #f5f5f5; padding:5px;">
								</div>
								<div class="floatleft" style="line-height:1.2; margin: 10px 1em 0 1em;">
									<span class="subscription-title">{{ item.name }}</span><br>
									<p style="font-size:1.2em;">{{ item.categories|joinby:" • "}}</p>
								</div>
								<div style="clear:both;"></div>
							</div>
							<div class="floatleft" style="margin-top:20px;">
								<a class="btn btn-following-desktop" href="javascript:void(0);" style=" width:67px; display:none;" onclick="javascript:unsubscribe({{ item.id }});"><i class="fa fa-check-circle"></i> Eliminar</a>
								<a class="btn btn-subscribe-desktop" href="javascript:void(0);" style=" width:67px;" onclick="javascript:subscribe({{ item.id }});"><i class="fa fa-plus-circle"></i> Suscr&iacute;beme</a>
							</div>
							<div style="clear:both;"></div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src='/static/lib/js/jquery.maskedinput-1.3.min.js'></script>
<script type="text/javascript">

var currentCity;

$(document).ready(function(){
	$( "#id_birthday" ).mask("99/99/9999");
	currentCity = $('#id_city').val();
	getCities(true);
});

$('#id_country').change(function(){
	getCities();
});

function getCities(firstLoad){
	jQuery.ajax({
  		type: "GET",
  		url: "{% url users_get 'cities'%}",
  		data: "country_id="+$('#id_country').val(),
		beforeSend: function(){
	  		$('button').attr('disabled',true);
  		},
	  	success: function(data){
	  		$('button').attr('disabled',false);
	  		if(data){
	  			json = eval(data);
	  			var html=''
	  			for (key in json){
	  				html+="<option value='"+json[key].pk	+"'>"+json[key].fields['name']+"</option>"
	  			}
	  			$('#id_city').html(html);
	  			if(firstLoad)
	  				$('#id_city').val(currentCity);
	  		}
	  	}
	});
}
function unsubscribe(company){
	subscribe(company, true);
}

function subscribe(company, unsubscribe){
	var post_url = "/comercios/subscribe/", subscribe = true;
	if(unsubscribe){ 
		post_url = "/comercios/unsubscribe/";
		subscribe = false;
	}
	jQuery.ajax({
  		type: "POST",
  		url: post_url,
  		data: 'company_id='+company,
		beforeSend: function(){
	  		$('button').attr('disabled',true);
	  		$("#loader").show();
  		},
	  	success: function(json){
	  		$('button').attr('disabled',false);
	  		$("#loader").hide();
	  		var data = eval(json);
	  		if (data[0].success==true){
	  			if(subscribe){
	  				$(".btn-following-desktop","div[data-companyid='"+company+"']").show();
	  				$(".btn-subscribe-desktop","div[data-companyid='"+company+"']").hide();
	  			}
	  			else{
	  				$(".btn-subscribe-desktop","div[data-companyid='"+company+"']").show();
	  				$(".btn-following-desktop","div[data-companyid='"+company+"']").hide();
	  			}
	  		}
		}
	});
}
</script>

{% endblock %}