crupzi/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

#from users.views import connect, newaccount, invite, invitation_request, complete_registration, account_configuration, account_operations, profile


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'crupzi.views.index', name='index'),
    url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/favicon.ico'}),
    url(r'^apple-touch-icon-precomposed\.png$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/apple-touch-icon-precomposed.png'}),
    url(r'^apple-touch-icon\.png$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/apple-touch-icon.png'}),
    url(r'^testfoursquare6/$', 'crupzi.views.testfoursquare', name='testfoursquare'),
    url(r'^testfoursquare-montesion/$', 'crupzi.views.testfoursquare_montesion', name='testfoursquare_montesion'),
    url(r'^beneficios/$', 'crupzi.views.features', name='features'),
    url(r'^comercios/$', 'crupzi.views.commerce', name='commerce'),
    url(r'^contacto/$', 'crupzi.views.contact', name='contact'),
    url(r'^nosotros/$', 'crupzi.views.us', name='us'),
    url(r'^soporte/$', 'crupzi.views.support', name='support'),
    url(r'^inicio/$', 'crupzi.views.home', name='home'),
    url(r'^tutoriales/$', 'django.views.generic.simple.redirect_to', {'url': 'http://www.youtube.com/playlist?list=PLhaYUqqgOkI3DduxrDZXw4Pt5UlO9guWX'}),
    url(r'^busqueda/$', 'deals.views.mobilesearch', name='mobilesearch'),
    url(r'^in/$', 'crupzi.views.new_user', name='new_user'),
    url(r'^logout/', 'crupzi.views.logout', name='logout'),
    url(r'^send_invitation/', 'crupzi.views.send_invitation', name='send_invitation'),
    url(r'^compartir/', 'crupzi.views.share', name='share'),
    url(r'^mobile/activacion/', 'crupzi.views.mobile_activation', name='mobile_activation'),
    url(r'^mobile/login/', 'crupzi.views.mobile_login', name='mobile_login'),
    url(r'^mobile/(?P<pub>[-\w]+)/solicitud/', 'crupzi.views.mobile_request', name='mobile_request'),
    url(r'^mobile/(?P<pub>[-\w]+)/', 'crupzi.views.mobile_pubs', name='mobile_pubs'),
    url(r'^comercios/connect/', 'crupzi.views.business_connect', name='business_connect'),
    url(r'^comercios/login/', 'crupzi.views.business_login', name='business_login'),
    url(r'^comercios/demo/', 'crupzi.views.business_login_demo', name='business_login_demo'),
    url(r'^comercios/inscripcion/', 'crupzi.views.business_signup', name='business_signup'),
    url(r'^comercios/logout/', 'crupzi.views.business_logout', name='business_logout'),
    url(r'^sendyapi/subscribe/', 'crupzi.views.sendy_subscribe', name='sendy_subscribe'),
    url(r'^sendyapi/unsubscribe/', 'crupzi.views.sendy_unsubscribe', name='sendy_unsubscribe'),
    url(r'^sendynewsletter/subscribe/', 'crupzi.views.sendy_subscribe_newsletter', name='sendy_subscribe_newsletter'),
    url(r'^suscripcion-exitosa-newsletter/', 'django.views.generic.simple.direct_to_template', {'template': 'mails/sendy-subscriptiondoubleopt.html', 'extra_context':  {'page': 'newsletter'} }  ),
    url(r'^suscripcion-exitosa-blog/', 'django.views.generic.simple.direct_to_template', {'template': 'mails/sendy-subscriptiondoubleopt.html', 'extra_context':  {'page': 'blog'}} ),
    url(r'^especiales/(?P<which>[-\w]+)/', 'crupzi.views.specials', name='specials'),
    url(r'', include('social_auth.urls')),
    url(r'', include('fakes.urls')),
    url(r'', include('deals.urls')),
    url(r'', include('companies.urls')),
    url(r'', include('users.urls')),
    url(r'^login/$', 'crupzi.views.login_user', name='crupzi_login'),
    # url(r'^crupzi/', include('crupzi.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)

deals/urls.py
from django.conf.urls import patterns, include, url
from deals.views import get_public_data, get_deal, save_deal, remove_deal, deal_search, search_box_input, search_get, single_deal, get_social, search_query, get_user_deal

urlpatterns = patterns('',
	url(r'^busqueda/', deal_search, name='deal_search'),
	url(r'^descuentos/(?P<slug>[-\w]+)/', single_deal, name='single_deal'),
	url(r'^search-box/get/(?P<what>\w+)/', search_box_input, name='search_box_input'),
	url(r'^search/query/', search_query, name='search_query'),
	url(r'^search/get/(?P<page>\w+)/', search_get, name='search_get'),
	url(r'^user-deals/get/code/(?P<deal_id>\w+)/', get_user_deal, name='get_user_deal'),
	url(r'^deals/get/code/(?P<deal_id>\w+)/', get_deal, name='get_deal'),
	url(r'^deals/get/social/(?P<deal_id>\w+)/', get_social, name='get_social'),
	url(r'^deals/get/(?P<category>\w+)/(?P<tab>\w+)/', get_public_data, name='get_public_data'),
	url(r'^deals/save/(?P<deal_id>\w+)/', save_deal, name='save_deal'),
	url(r'^deals/remove/(?P<deal_id>\w+)/', remove_deal, name='remove_deal'),
)

companies/forms.py
# -*- coding: utf-8 -*-
import os
from PIL import Image
from cropresize import crop_resize
from django import forms
from django.conf import settings
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from users.models import Country
from companies.models import Company

class CompanyInfoForm(forms.Form):
	name = forms.CharField(label='Nombre', required=True)
	adddress = forms.CharField(label='Direccion', required=False)
	
class CompanyLogoForm(forms.Form):
	logo = forms.ImageField(required=False)
	def save(self, company, files):
		#display uploads.
		display = files.get('logo')
		if display is not None:
			filename = company.slug+'__'+display.name
			path = os.path.join(settings.UPLOAD_URL_LOGOS,'logos/'+filename)
			destination = open(path,'wb+')
			for chunk in display.chunks():
				destination.write(chunk)
			destination.close()
			try:
				img = Image.open(path)
				resized_img = crop_resize(img,(56,56))
				resized_img.save(os.path.join(settings.UPLOAD_URL_LOGOS,'logos_56/56x56_'+filename))
				setattr(company, 'logo',filename)
				company.save()
			except Exception,e:
				print e
			

crupzi/views.py
# -*- coding: utf-8 -*-
import datetime
import locale
import zlib
import urllib, urllib2
from mobileesp import mdetect
from django.contrib.auth import logout as auth_logout, authenticate, login
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.utils import simplejson
from django.views.decorators.csrf import csrf_exempt
from users.models import Country, Profile, MobileRequest
from companies.models import Company, CompanyCategory, CompanyUser, Branch, Mall
from companies.forms import CompanyLogoForm
from resources.models import Resource, ResourceEntity
from deals.models import Deal, DealResource, DealBranch
from crupzi.utils import get_schedule, sendy_api_request, sendy_double_opt_subscribe, sendy_api
from template_email import TemplateEmail
from django_mobile import get_flavour


def index(request):
	if request.user.is_authenticated() and not CompanyUser.objects.filter(user=request.user).exists():
		return HttpResponseRedirect('/inicio/')
	else:
		#get 3 random deals.
		today_date = datetime.date.today()
		deals_random = Deal.objects.raw("select * from  (select d.id, d.name, random() from deals_deal as d, companies_company as c where d.company_id = c.id and c.valid=true and d.valid=true and d.deleted=false and ( ('"+str(today_date)+"' between init_date and end_date) or ('"+str(today_date)+"' >= init_date and end_date is null)) ) d order by 3 limit 3")
		deal_list = list()
		for d in deals_random:
			deal = Deal.objects.get(id=d.id)
			schedule = get_schedule(deal.schedule)
			schedule_str = ', '.join(schedule)
			deal_resource = DealResource.objects.filter(deal=deal)
			deal_category = CompanyCategory.objects.filter(company=deal.company)
			deal_branch = DealBranch.objects.filter(deal=deal)
			locale.setlocale(locale.LC_TIME,'es_ES')
			if deal.end_date:
				end_date = deal.end_date.strftime("%d de %B de %Y")
			else:
				end_date = None
			deal_list.append(dict(deal=deal, end_date=end_date, schedule=schedule_str, resources=deal_resource, categories=deal_category, branches=deal_branch))
		malls = Mall.objects.filter(country_id=1).order_by('name')
		companies = Company.objects.filter(country_id=1, valid=True).order_by('name')
		resources = Resource.objects.filter(country_id=1, valid=True).order_by('entity')
		return render_to_response('landing/index.html',{'deals': deal_list,'malls':malls,'companies':companies, 'resources': resources}, RequestContext(request))

def login_user(request):
	if request.user.is_authenticated():
		if CompanyUser.objects.filter(user=request.user).exists():
			return HttpResponseRedirect('/comercios/dashboard/inicio')
		return HttpResponseRedirect('/inicio/')
	else:
		today_date = datetime.date.today()
		print today_date
		deals_random = Deal.objects.raw("select * from  (select id, name, random() from deals_deal where valid=true and deleted=false and (('"+str(today_date)+"' between init_date and end_date) or ('"+str(today_date)+"' >= init_date and end_date is null))) d order by 3 limit 3")
		deal_list = list()
		for d in deals_random:
			deal = Deal.objects.get(id=d.id)
			schedule = get_schedule(deal.schedule)
			schedule_str = ', '.join(schedule)
			deal_resource = DealResource.objects.filter(deal=deal)
			deal_category = CompanyCategory.objects.filter(company=deal.company)
			deal_branch = DealBranch.objects.filter(deal=deal)
			locale.setlocale(locale.LC_TIME,'es_ES')
			if deal.end_date:
				end_date = deal.end_date.strftime("%d de %B de %Y")
			else:
				end_date = None
			deal_list.append(dict(deal=deal, end_date=end_date, schedule=schedule_str, resources=deal_resource, categories=deal_category, branches=deal_branch))
		return render_to_response('landing/login.html',{'deals':deal_list}, RequestContext(request))

def features(request):
	return render_to_response('landing/features.html',{}, RequestContext(request))

def commerce(request):
	return render_to_response('landing/companies.html',{}, RequestContext(request))

def contact(request):
	return render_to_response('landing/contact.html',{'inverse_social':True}, RequestContext(request))

def us(request):
	return render_to_response('landing/us.html',{'inverse_social':True}, RequestContext(request))

def support(request):
	return render_to_response('landing/support.html',{}, RequestContext(request))

def home(request, new_user_modal=False):
	if request.user.is_authenticated() and not CompanyUser.objects.filter(user=request.user).exists():
		country_id, display = Profile.objects.values_list('country_id','display').filter(user=request.user)[0]
		notification = False
		user_profile = True
	else:
		user_profile = False
		country_id = 1
		display = None
		new_user_modal = False
		notification = False
	if get_flavour(request)=='mobile' and request.GET.get('query')=='1':
		return HttpResponseRedirect('/busqueda/?'+request.META['QUERY_STRING'])
	if not request.user.is_authenticated():
		if (request.is_mobile or request.is_phone) and not request.is_tablet and request.META['QUERY_STRING'] == "":
			return mobile_login(request)
	countries = Country.objects.values('id','name')
	today_date = datetime.date.today()
	extra_where = [" (('"+str(today_date)+"' between init_date and end_date) or ('"+str(today_date)+"' >= init_date and end_date is null))"]
	deals = Deal.objects.values('id','name','schedule', 'company_id').filter(country_id=country_id, valid=True, deleted=False).extra(where=extra_where).order_by('-saves_count','-click_count')[:5]
	favs = list()
	for deal in deals:
		company = Company.objects.values('name','slug','logo').filter(pk=deal['company_id'])[0]
		category = CompanyCategory.objects.values_list('category_id', flat=True).filter(company_id=deal['company_id'])
		schedule = get_schedule(deal['schedule'])
		schedule_str = ', '.join(schedule)
		favs.append(
			dict([('id',deal['id']),('name',deal['name']),('schedule',schedule_str),
				('company',company.get('name')),('category',category),('company_slug',company.get('slug')), ('company_logo', company.get('logo')) ])
		)
	malls = Mall.objects.filter(country_id=1).order_by('name')
	companies = Company.objects.filter(country_id=1, valid=True).order_by('name')
	resources = Resource.objects.filter(country_id=1, valid=True).order_by('entity')
	return render_to_response('app/app-home.html',{'countries':countries,'user_country':country_id,'display': display, 'favs': favs, 'is_tablet': request.is_tablet or False,
		'malls':malls,'companies':companies, 'resources': resources, 'new_user': new_user_modal, 'notification': notification, 'user_profile': user_profile, 'page':'home'}, RequestContext(request))

def new_user(request, backend=None):
	return home(request, True)

def business_login(request):
	if request.user.is_authenticated():
		if CompanyUser.objects.filter(user=request.user).exists():
			if request.user.username!='crupzi-demo':
				return HttpResponseRedirect('/comercios/dashboard/inicio')
			else:
				auth_logout(request)
	return render_to_response('dashboard/dashboard-login.html',{}, RequestContext(request))

def business_login_demo(request):
	if request.user.is_authenticated():
		if CompanyUser.objects.filter(user=request.user).exists():
			return HttpResponseRedirect('/comercios/dashboard/inicio')
	return render_to_response('dashboard/dashboard-login.html',{'demo': True}, RequestContext(request))	

def business_signup(request):
	return render_to_response('landing/companies-signup.html',{}, RequestContext(request))	

def business_logout(request):
	logout_url = '/comercios/demo' if request.user.username=='crupzi-demo' else '/comercios/login'
	auth_logout(request)
	return HttpResponseRedirect(logout_url)

def business_connect(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				try:
					company = CompanyUser.objects.get(user=user)
					login(request, user)
					return HttpResponseRedirect('/comercios/dashboard/inicio')
				except CompanyUser.DoesNotExist:
					error = 'No existe una compania asociada su cuenta de usuario.'
			else:
				error = 'Su cuenta de usuario se encuentra desactivada'
		else:
			error = 'La combinacion usuario/contrasena ingresada no existe.'
	return render_to_response('dashboard/dashboard-login.html',{'username': username, 'error': error}, RequestContext(request))

def business_dashboard_stats(request):
	return render_to_response('dashboard/dashboard-stats-gral.html',{}, RequestContext(request))

def logout(request):
	auth_logout(request)
	return HttpResponseRedirect('/')

@csrf_exempt
def send_invitation(request):
	if request.user.is_authenticated():
		if request.POST.get('email-url') or request.POST.get('email-url')!='':
			errors = list(['Se encontraron errores en la solicitud.'])
			response = [dict(error=True, errors=errors)]
		else:
			try:
				email_from = "Crupzi.com <info@crupzi.com>"#request.user.email
				email_to = request.POST.get('email-to').split(',')
				email_msg = request.POST.get('email-msg')
				context = {'from_user': request.user.first_name+' '+request.user.last_name, 'user_message': email_msg}
				email = TemplateEmail(template='mails/email-share.html', context=context, to=email_to, from_email=email_from)
				email.send()
				response = [dict(error=False)]
			except Exception,e:
				print e
				errors = list(['Se encontraron errores en la solicitud.'])
				response = [dict(error=True, errors=errors)]
		json = simplejson.dumps(response)
		return HttpResponse(json, content_type='application/javascript')


def testfoursquare(request):
	return render_to_response('pruebafoursquare.html',{}, RequestContext(request))

def testfoursquare_montesion(request):
	return render_to_response('pruebafoursquare2.html',{}, RequestContext(request))

crupzi/templates/dashboard/dashboard-login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- Always force latest IE rendering engine or request Chrome Frame -->
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <!-- Use title if it's in the page YAML frontmatter -->
  <title>Crupzi.com - Inicio de sesi&oacute;n para comercios</title>

  <link href="/static/lib/dashboard/stylesheets/application.css" media="all" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800">
  <script src="/static/lib/dashboard/javascripts/application.js" type="text/javascript"></script>

  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!-- there's an IE separated stylesheet with the following resets for IE -->
  <!--[if lte IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script src="../../javascripts/html5shiv.js" type="text/javascript"></script>
        <script src="../../javascripts/excanvas.js" type="text/javascript"></script>
        <script src="../../javascripts/ie_fix.js" type="text/javascript"></script>
        <link href="../../stylesheets/ie_fix.css" media="screen" rel="stylesheet" type="text/css" />
  <![endif]-->
  <style>
      section#main {  margin-left: 0px; }
      ul.top-notifications { display: none; }
  </style>
</head>
<body>
<div class="top-bar">
  <a id="topbar-brand-out" class="brand" href="">
    <img alt="Dashboard Crupzi.com" src="/static/images/landing/logo.png" width="100" style='margin-top:10px;'/>
  </a>
</div>
<section id="main">
  <div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="login-container center">
        <div>
          <img src="/static/images/logo_blog.png" width='220px' style='margin-right:47px;'/>
          <img src="/static/images/app/afiliado-new-small.png">
        </div>
  <div class="title text-transparent" style='font-size:25px; margin-top:10px; text-align:center;'>
    {% if demo %}
    Versi&oacute;n demo de Comercios
    {% else %}
    Inicio de Sesi&oacute;n Comercios
    {% endif %}
  </div>
  <hr class="main">
  {% if error %}
	<div class="alert alert-error" style='margin-top:1.5em;'>
		{{ error }}
	</div>
	{% endif %}
  <form id='form_businessConnect' action='/comercios/connect/' method='post' class='login-form'>{% csrf_token %}
    <ul class="fields-list">
      <li>
        <i class="icon-user" style="float: left;"></i>
        <input autocomplete="off" id="username" name="username" placeholder="Nombre de usuario" type="text" value="{% if demo%}crupzi-demo{% endif %}">
      </li>
      <li>
        <i class="icon-key"></i>
        <input autocomplete="off" id="password" name="password" placeholder="Contrase&ntilde;a" type="password" value="{% if demo%}crupzidemo{% endif %}">
      </li>
    </ul>

    <div class="actions">
      <a href="javascript:void(0);" class="btn btn-large medium-blue login-btn" id='btn-connect'>
        Iniciar Sesi&oacute;n
      </a>
    </div>

    <hr class="main">
    {% if demo %}
    <p>
      En la versi&oacute;n demo no puedes hacer modificaciones dentro de la plataforma.<br><br> Para ingresar solamente presiona el bot&oacute;n<br> "Iniciar Sesi&oacute;n"
    </p>
    {% else %}
    <h3>&iquest;Olvidaste tu contrase&ntilde;a?</h3>
  	<p>
  		No hay problema, <a href="/comercios/passwordreset/">Click aqu&iacute;</a> para obtener una nueva.
  	</p>
    {% endif%}
  </form>
</div>
    </div>
  </div>
</div>
</section>
<script type="text/javascript">

	$('#password').keypress(function(e){
		 var code = (e.keyCode ? e.keyCode : e.which);
		 if(code == 13) { //Enter keycode
			$('#btn-connect').click();		   
		 }
	});

	$('#btn-connect').click(function(){
		$('#form_businessConnect').submit();
	});
</script>
</body>
</html>

crupzi/templates/dashboard/dashboard-settings.html
{% extends 'dashboard/dashboard-base.html' %}

{% block dashboard-title%}Dashboard - Inicio{% endblock %}

{% block active-ini %}active{% endblock %}

{% block pagetitle %}Configuraci&oacute;n {% endblock %}

{% block dashboard-content %}




<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="box bordered">
				<div class="box-header">
              		<i class="icon-picture"></i> Informaci&oacute;n General
              	</div>
              	<div class=''>
              		<div class='alert alert-success' id='msg-info-success' style='display:none; margin:1em 30px;'></div>
              		<div class="alert alert-error" style='display:none; margin:1em 30px;' id='info-form-errors'></div>
              	</div>
              	<div>
              		<div class='span4'>
              			<div class='padded' style='margin-top:-20px;'>
              				<div class='section-title'>Informaci&oacute;n vigente</div>
              				<span class='bold'>Nombre: </span><span id='lbl-businessname'>{{company.name}}</span><br>
							<span class='bold'>Direcci&oacute;n:</span>
							{% if company.address %}
								<span id='lbl-businessaddress'>{{company.address}}</span>
							{% else%}
								<span id='lbl-businessaddress'>-----------</span>
							{% endif %}
							<br>
							<span class='bold'>Tel&eacute;fono:</span>
							{% if company.phone_number %}
							 	<span id='lbl-businessphone'>{{ company.phone_number }}</span>
							{% else%}
								<span id='lbl-businessphone'>-----------</span>
							{% endif %}
							<br><br>
							<button class='btn dark-blue btn-mini' onclick='javascript:info_changeInfo();' style=''>Modificar informaci&oacute;n</button>
              			</div>
              			
              		</div>

              		<div class='span5 padded' style='margin-top:-20px;'>
              			
              			<div id='info-form-container' style='display:none;' >
              				<div class='section-title'>Modificaci&oacute;n de Informaci&oacute;n general</div>
              				<div class=''>
              					<div class=''>
									<form id='form-changeinfo' name='form-changeinfo'>
							    		<div>
											<div><span class='bold'>Nombre</span></div>
											<div><input type='text' id='txt-business_name' name='txt-business_name' style='width:90%;'/></div>
										</div>
										<div>
											<div><span class='bold'>Direcci&oacute;n</span></div>
											<div><textarea rows='4' id='txt-business_address' name='txt-business_address' style='width:90%;'></textarea></div>
										</div>
										<div>
											<div><span class='bold'>Tel&eacute;fono</span></div>
											<div><input type='text' id='txt-business_phonenumber' name='txt-business_phonenumber' style='width:90%;'/></div>
										</div>
										
									</form>
									<div class='' style=''>
										<button class='btn dark-blue btn-mini' id='btn-info_changeinfo' style=''>Cambiar</button>
										<button class='btn btn-mini' id='btn-info_cancelchangeinfo'>Cancelar</button>
									</div>
									<br>
								</div>
              				</div>
              			</div>
              		</div>
              		<div style='clear:both;'></div>
              	</div>
          	</div>
      	</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="box bordered">
				<div class="box-header">
              		<i class="icon-picture"></i> Cambio de logo
              	</div>
              	<div class='padded'>
	              	<div class='span4' style='margin-left:0;'>
	              		<div class=''>
	              			<form id='form-logo' action="/comercios/data/logo/" method="post" enctype="multipart/form-data">{% csrf_token %}
							{% for field in logoForm %}
								<div class="fieldWrapper inline-fields">
									<div>{{ field }} <button class='btn dark-blue btn-mini' id='btn-changeimg'>Cambiar imagen</button></div>
								</div>
							{% endfor %}
							</form>
	              		</div>
	              	</div>
              	</div>
              	<div style='clear:both;'></div>		
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="box bordered">
				<div class="box-header">
              		<i class="icon-picture"></i> Cambio de contrase&ntilde;a
              	</div>
				<div class='padded'>
					<div class="alert alert-error" style='display:none;' id='info-pwd-msg'></div>
					<div class="alert alert-error" style='display:none;' id='info-pwd-errors'></div>
					<form id='form-changepwd'>
			    		<div style='position:relative;'>
							<div class='floatleft' style='width: 150px;'><span class='bold'>Nueva contrase&ntilde;a: </span></div>
							<div class='floatleft'><input type='password' id='txt-businesspwd' name='txt-businesspwd' data-typetoggle='#chk-showpassword'/ style='width:90%;'></div>
							<div style='clear:both;'></div>
						</div>
						<div>
							<input id="chk-showpassword" type="checkbox" style='margin-top:-5px;' style='width:90%;'/><span style='margin-left:5px;'>Mostrar contrase&ntilde;a</span>
						</div>
						
					</form>
					<div class='' style=''>
						<button class='btn dark-blue btn-mini' id='btn-info_changepwd' style=''>Cambiar</button>
						<button class='btn btn-mini' id='btn-info_cancelchangepwd'>Cancelar</button>
					</div>
				</div>
			</div>
		</div>
		<div style='clear:both;'></div>
	</div>
</div>

<div>
	

	<div class="box">

		<div class="box-content">
			<div class='span4 floatleft' style='margin-bottom:15px;'>
				
				<!-- <a href="javascript:void(0);" onclick='javascript:info_changeInfo();'>Modificar informaci&oacute;n</a>&nbsp;&nbsp;
				<a href="javascript:void(0);" onclick='javascript:info_changePwd();'>Cambiar contrase&ntilde;a</a> -->
			</div>
			<div class='floatleft span4'>
				<div class="box-header" data-original-title>
					<h2></span></h2>
				</div>
				
			</div>
			<div id='info-form-password' class='floatleft span4' style='display:none; margin:0;'>
				
			</div>
			<div style='clear:both;'></div>
		</div>
	</div>
	<br>
</div>

<div class='modal hide' id='modal-passwordConfirm'>
	<div class='modal-header'>
		<button type="button" class="close" data-dismiss="modal">×</button>
		<h3>Est&aacute; apunto de cambiar su contrase&ntilde;a</h3>
	</div>
	<div class='modal-body' id='modal-deal-save-body'>
		<p>
			&iquest;Est&aacute; seguro que desea continuar?
		</p>
	</div>
	<div class="modal-footer">
		<a href="javascript:changePassword();" class="btn btn-primary">S&iacute;</a>
		<a href="javascript:$('#modal-passwordConfirm').modal('hide')" class="btn" data-dismiss="modal">No</a>
	</div>
</div>

{% endblock %}

{% block scriptjs %}

<script type="text/javascript" src='/static/lib/js/jquery.password_strength.js'></script>
<script type="text/javascript" src='/static/lib/js/jquery.showpassword.js'></script>


<script type="text/javascript">

$('#id_logo').uniform();
$('#txt-businesspwd').showPassword();

</script>

<script type="text/javascript" src='/static/lib/js/app/companies/dashboard_info.js'></script>
{% endblock %}